var days = [
  {
    day: "day_1",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: ["ryan's room mates are cool", "ryan", "longboarding"],
    date: "",
    location: "Baltimore to Princeton",
    miles: 338,
    text: "",
  },
  {
    day: "day_2",
    date: "",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "princeton",
      "princeton",
      "new ride + setup",
      "bridge off manhattan",
      "steam",
      "sky",
      "boat",
      "night",
      "the setup",
      "chinatown",
      "copping out",
      "goodbye",
    ],
    location: "Princeton to Long Island",
    miles: 701,
    text: "",
  },
  {
    day: "day_3",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "up all night",
      "nice view",
      "sky",
      "sky",
      "ferry",
      "amtrack",
      "new london",
      "train",
      "new london",
      "cold",
      "new london",
      "at harvard w/ween",
      "h*rvard",
    ],
    date: "",
    location: "Long Island to Boston",
    miles: 64,
    text: "",
  },
  {
    day: "day_4",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    location: "Boston to Baltimore",
    captions: ["clocking in"],
  },
];

export default days;
