var days = [
  {
    day: "day_1",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "at our amazing viewpoint sleeping place",
      "heading out",
      "rural washington",
      "simon driving",
      "simon driving more",
      "bridge",
      "bridge 2",
      "sunset",
    ],
    date: "07/24/20",
    location: "Seattle to Ocean Beach Picnic Area",
    miles: 338,
    text:
      "After learning how to drive stick the day before we headed out at around 3pm. Before leaving we stopped at walmart for snacks and some random things. It took us a few hours but we managed to leave seattle without crashing the car and only stalling out a couple times in intersections/traffic. Spent most of the drive talking, once we got to Portland it was dark. We went to Olive Garden right before they closed and got take out. We decided to drive a few more hours after eating (because we hadn't planned out where to sleep yet). We also looked at the map for a bit and decided that we would be taking the highway along the ocean. We talked more and watched a few Simpsons episodes up until 2am. Towards the end of our day we started looking for campsites but all of them were full, oops. After a few miles of searching we found a veiwpoint on the side of the highway and pulled behind a parked RV. We leaned our seats back and then went to sleep.",
  },
  {
    day: "day_2",
    date: "07/25/20",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "our sleeping place",
      "brushing teeth",
      "lucy cute",
      "simon",
      "lucy at the sand dunes",
      "simon falling down",
      "beautiful coasts of oregon",
      "us",
      "ron",
      "lucy climbing",
      "more coasts",
      "feeties",
      "redwoods",
      "lucy in the redwoods",
      "more redwoods",
      "us",
      "coasts",
      "simon driving",
      "coasts",
      "feeties",
      "coast",
    ],
    location: "Ocean Beach Picnic Area to Gray Whale Cove Trail Parking Lot",
    miles: 701,
    text:
      "We woke up somewhat disoriented. It was still a bit chilly, and the windows were covered with condensation. Once we stepped outside, though, the ocean view made our roadside sleep worth it. We drove for a bit to find a bathroom, and then got ready for the day, which would end up taking us 700 miles. Our first stop was at the Sea Lion Caves, which boasted America’s largest sea cave. We didn’t want to pay admission, so we just took some pictures of the coast and left. We drove through a couple of towns, including Florence and North Bend. In Point Orford, the westernmost town in the lower 48, we got out and walked on the beach. We grabbed lunch at a Subway in Brookings just before crossing into California (when asked at the border whether we were carrying any fruits or vegetables, Simon said “just the spinach on this Subway sandwich”). Now in California, we knew we needed to see some redwoods. There are a lot of spots to see them, but we decided to drive down the Newton B Drury Scenic Parkway. We had the road to ourselves, and we stopped to take some pictures with these huge trees. After the redwoods, we pretty much drove straight through to San Francisco, stopping only in Eureka to eat In-N-Out on the waterfront (when in California). We arrived in SF around 2:30am. We had planned to sleep at a viewpoint near the Golden Gate Bridge, but changed our minds when we saw a park vehicle. After calling a couple of cheap motels that were all full, we decided to drive out of the city to find a viewpoint along the highway. But first, I (Lucy) had to pee. After striking out with public restrooms, I ended up shamefully squatting behind the sign for the San Francisco Marina Small Craft Harbor. Desperate times. After filling up on gas, we drove out of the city to Gray Whale Cove Trail Parking Lot, where we finally got to sleep around 4:30am.",
  },
  {
    day: "day_3",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "climbing after peeing",
      "nice view",
      "lighthouse",
      "cali gettin hot",
      "thermometer girl with the ice",
      "a huge hill",
      "mountain",
      "LA",
      "LA",
    ],
    date: "07/26/20",
    location: "Gray Whale Cove Trail Parking Lot to Los Angeles",
    miles: 64,
    text:
      "We woke up to a parking lot full of hikers. Again, we had underestimated the West Coasters. We quickly pulled out and drove until we found a bathroom. We got changed and climbed over the edge of the parking lot for a beautiful ocean view. Today we were driving to LA, where we had already reserved a motel room (we desperately needed showers). Our first stop was just a quick turn out, where we took pictures of an awesome old lighthouse. Our next stop was really out of desperation. The heat hit suddenly, and hard. We had been feeling optimistic about our lack of A/C up until now, but SoCal was a different beast. We stopped at a gas station to buy an Icee drink and a bag of ice, and we rubbed the ice cubes on our faces and arms while we drove. We took a long break in the shade of a picnic shelter, and then we finally made it to LA. We went to our motel, where we took showers and ordered in some Chipotle. Once the sun had set, we drove into Hollywood to see the Walk of Fame. It was a beautiful night, and the perfect temperature for walking around. After exploring for a while, we returned to the motel for a great sleep.",
  },
  {
    day: "day_4",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "the ac",
      "tower",
      "the desert",
      "road",
      "gas",
      "bridge",
      "casino",
      "road",
      "Las Vegas",
      "trees",
      "street",
      "inside the hotel",
      "street",
      "art",
      "the strip",
      "ice cream",
      "casino",
      "biggest chocolate fountain",
      "buildings",
      "lucy and flowers",
      "us",
      "lucy",
      "midnight",
    ],
    date: "07/27/20",
    location: "Los Angeles to Las Vegas",
    miles: 0,
    text:
      "We slept in, and then spent some time researching portable air conditioners. After watching a YouTube tutorial, we decided to make our own A/C out of a styrofoam cooler, a desktop fan, two metal tubes, and a bag of ice (see picture). Unfortunately, it only worked in principle because the fan wasn’t powerful enough when we ran it off of the car’s battery. No matter, we only had to drive through 115ºF heat on our way to Las Vegas! We made the best of the day, driving along historic U.S. Route 66 and stopping at the famous Bottle Tree Ranch and train car McDonald’s. It was a short four hour drive, and we were in Vegas by 7pm. Just driving into Vegas was an experience in and of itself, with huge hotel-casinos and gaudy attractions appearing out of nowhere in the middle of the desert. As a surprise for my 20th birthday, Simon had made us a reservation at the Bellagio! We had to walk through the entire casino to get to our room, and we definitely stuck out. Everyone was already dressed up for dinner and gambling, and we were sweaty and carrying a trash bag full of our dirty clothes. We made it to our room, showered and changed, and ate some dinner at a counter-service restaurant called Snacks in the casino. Had some delicious sandwiches and met a guy that was also on a road trip. He had spent some time in Alaska as a kid, and said we should make our way up to Utqiagvik whenever we were back there. We spent the rest of the night walking up and down the strip, which was definitely a sight to see (and hot, even after the sun had set). We walked through a bunch of the casinos, marveling at the elaborate themes (the Luxor, which is a giant, black, and Egyptian-themed pyramid, was a personal favorite). We got back to the Bellagio just in time for the last fountain display! Simon was of course trying to figure out just how much force it would take to shoot water that high. We had planned on staying up to celebrate some more, but after Simon gave me my birthday gift (an amazing photo album and a Spotify playlist for the rest of the trip) and we watched an episode of Futurama, we passed out. ",
  },
  {
    day: "day_5",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "07/28/20",
    location: "Las Vegas",
    miles: 259,
    captions: [
      "the road",
      "artsy",
      "rocks",
      "lucy",
      "the open road",
      "car",
      "terrain",
      "simon fixing the ac",
      "road",
      "crazy",
      "capitol",
      "road",
    ],
    text:
      "We thought we might try to go to the pool early in the morning, but we decided to sleep in instead. We checked out at 11am and started the drive to Salt Lake City, UT. It was a relatively short and beautiful drive through canyons and fields. We took a break at a gas station and Simon spent some time updating the DIY A/C, which was definitely improved but was still no match for the desert. Everything really worked out for us this day, and we ended up at this beautiful campground at the edge of the city called Cherry Hill (it had showers, which was key). We went to a Mexican drive-thru restaurant for dinner, and definitely had the best food of the trip so far. There was not a cloud in sight, so we kept the rainfly off and slept under the stars. ",
  },
  {
    day: "day_6",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/17/19",
    location: "South Bend to Chicago",
    miles: 0,
    captions: [
      "what is this guy wearing",
      "road",
      "clouds",
      "walking by geysers",
      "woah",
      "lucy",
      "crazy stuff",
      "big geyser",
      "cool",
      "chip",
      "old faithful",
      "a guy and old faithful",
      "our campsite",
      "cant forget",
      "lol",
      "nice view",
      "our home",
    ],
    text:
      "Simon woke up early for class, and we started driving about an hour later. Today was Yellowstone day! We stopped at WalMart for more snacks, and then drove for about four hours to reach the town of West Yellowstone. We stopped for ice cream and then entered the park. We quickly found that it’s hard to not stop for everything, so we did. We saw geysers, boiling pools, and mud features. We then got stuck in a very long line of cars for the Old Faithful viewpoint. By the time we got to the parking lot, we still hadn’t figured out where the geyser actually was or when it was supposed to go off. We walked into the gift shop and the employee at the door told us that it was set to go off in about three minutes and it was about a quarter mile that way. We started running and made it just as the geyser was beginning to spew out of the ground. It only lasted for a few minutes, and we got back to the car right as it started to pour down rain. After another thirty minutes of waiting in line to exit the parking lot, we made our way to our campsite, only to find it flooded with water. We told the campground managers about it, and they said they would shovel it out (???) while we went to grab some food and do our laundry. I also called my friends (despite terrible service), and it was great to hear all of their voices and catch up. When we got back to the campground, they had given us a new site, but by then it was dark and we just slept in Ran anyway. We were glad that we had a windshield covering because apparently our campsite doubled as the trail to the bathroom, and there were people passing through all night. We also heard wolves howling in the distance just before we fell asleep.",
  },
  {
    day: "day_7",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/16/19",
    location: "Angola to South Bend",
    miles: 75,
    captions: [
      "what a view",
      "bison",
      "cliffs",
      "bison up close",
      "canyon",
      "baby bison!",
      "waterfall",
      "spring",
      "spring",
      "simon",
      "spring",
      "orange",
      "spring",
      "crazy",
      "nice",
      "fields",
      "fields",
      "bison just chillin",
      "bison chillin",
      "crazy landscape",
      "mountains",
      "going up",
      "crazy landscape",
      "altimeter",
      "cool",
      "top of the world",
      "lake",
      "road",
      "lake",
      "lake",
      "mountain pass",
      "lucy",
      "mountains",
      "lucy",
      "sunset",
      "us",
      "lucy and the altimeter",
      "us",
    ],
    text:
      "This was definitely one of the coolest days of the entire trip. We underestimated the size of Yellowstone, and spent most of the day exploring the rest of the park. We saw a bunch of bison (a whole herd crossed the boardwalk right in front of us, which was actually terrifying). We saw more of the amazing scenery and geological features, including the Grand Canyon of Yellowstone and the Mammoth Hot Springs, which at first glance looks like snow but is actually pure white rock. We stopped at the Albright Visitor Center, which is advertised as the only place in the park with WiFi, to plan our next move. We had hoped to make it to Rapid City that night, but we had already spent too much time in Yellowstone. Instead, we found Green Tree’s Crazy Woman Campground in Gillette, WY. Seemed perfect. After leaving Yellowstone, we stopped in a small town called Cooke City for lunch, then navigated towards Gillette. To get there, we had to drive through an amazing mountain pass. We stopped at the Top of World Store, which boasted an elevation of 9400 feet, and we were still climbing after that. Ran never faltered, and we made it to the top of the pass with no trouble. The rest of the day was just a pretty plain drive to Gillette (lots of fields). We did stop at a gas station with gas for only $1.99/gallon, which was very exciting. We pulled into the Crazy Woman Campground late, showered, cooked ramen for dinner, and slept. ",
  },
  {
    day: "day_8",

    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/15/19",
    location: "Toledo to Angola",
    miles: 81,

    captions: [
      "mt rushmore",
      "us",
      "faces",
      "badlands",
      "landscape",
      "beast",
      "posted up",
      "bison",
      "rock",
      "bison and lucy",
      "rock",
      "simon",
      "rock",
      "rock",
      "rock",
      "lucy",
      "rock",
      "rock",
      "rock",
      "rock",
      "rock",
      "cool pic",
    ],
    text:
      "Another really cool day. We left Gillette fairly early (Simon was up for class) and drove to Mt Rushmore. We were almost there when we stopped for a sign that was advertising helicopter tours of Mt Rushmore for just $49.99 (!!!). Simon went inside, only to learn that not only was it $50 per person, but that was the price for just a six-minute flight around their facility. The tour of Mt Rushmore was actually $200 per person. Disappointing. We made it Mt. Rushmore, which really was breathtaking, especially after we learned more about its construction. We took pictures with both the Alaska and Puerto Rico flags on the Avenue of Flags, and we got some really good lemonade that was made with berries and honey from the Black Hills. After Mt Rushmore, our next stop was Badlands National Park. We didn’t really know what to expect, but Simon remembered several people telling him that he should check it out during his bike trip. Our navigation took us to the back entrance of the park (we didn’t have to pay, and Simon got to try drifting on the dirt roads), and our first stop was called Prairie Dog Town. We saw a bunch of prairie dogs, which are really funny looking. On all fours they walk like dogs, but then they’ll stand up on their hind legs and look around, and they crouch down in a really weird position when they’re eating. After the prairie dogs, we started to see the amazing rock formations of the Badlands. Kind of like Vegas in the desert, the badlands really just come out of nowhere. One second you’re surrounded by cornfields, the next you’re looking out over these multicolored cliffs. We saw some bison here too, in particular one that was just sitting by himself on the edge of a cliff (hope he’s doing okay). We spent a lot of time in the Badlands, getting out and walking around among all the different types of rock. It was really beautiful, and I would definitely recommend this park to anyone who’s nearby. Disclaimer: I got a bloody nose (stay hydrated) and used a truly disgusting bathroom, so be warned. After the Badlands, we stopped for gas and drove to Sioux Falls (through a crazy downpour), where we stayed in a motel. We showered (I know I keep pointing this out, but it really did feel like an event after spending a hot day in Ran), ordered in Buffalo Wild Wings, and watched Mad Max: Fury Road. (For anyone who’s watched or is thinking about watching, I would highly recommend this behind the scenes video: https://www.youtube.com/watch?v=yKAHGwCyamc. It’s seriously impressive, and that’s coming from someone who couldn’t care less about cars or blowing shit up).",
  },
  {
    day: "day_9",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/14/19",
    location: "Toledo",
    miles: 0,
    captions: ["new state", "madison", "madison bikers"],
    text:
      "A long day of driving. We drove from Sioux Falls to Madison, WI. We (Simon) got pulled over for speeding in Minnesota, but we got off with a warning. The trooper got a kick out of our homemade A/C, and the fact that it was obviously not working because I was only wearing a sports bra and sporting like three empty bottles of Body Armour at my feet. We stopped in Madison for dinner, and walked around the city center a bit. Then we drove to Arlington Heights, which is about an hour north of UChicago. Highlights: really nice rest stop at the entrance into Wisconsin from Minnesota. ",
  },
  {
    day: "day_10",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/13/19",
    location: "Case Western Reserve University to Toledo",
    miles: 120,
    captions: [
      "road",
      "chicago",
      "road",
      "covid is not real",
      "nice road",
      "weird looking guy eating a steak",
      "toledo",
      "toledo at night",
    ],
    text:
      "Spent a lot of time in Chicago moving my stuff into a new storage unit. Woke up really early to check in at the new unit. Then drove to my friend’s apartment, where I picked up my plants (<3) and the key to her storage. Drove to her unit, moved our stuff in and my stuff into Ran (got it all to fit in one go, there is really nothing he cannot do), and moved it to the new spot. Cleaned up Ran a bit while he was empty, went to pick up our stuff, and then drove to Hyde Park to see Xavier!!! So good to see his face again, and thank you for taking care of my plants (<3). After all the Chicago business was wrapped up, we grabbed a milkshake from the Med (essential) and drove to Indiana Dunes State Park. It was too crowded for comfort, but we dipped our feet in the water and drove through the campgrounds. Excited to be back in Chicago with a car so we can go camping! We made some calls to COVID testing facilities in Maryland (we wanted to get tested before going to Simon’s house) and found out that a clinic in Germantown was supposed to get a shipment of rapid tests the next morning. We had planned to stay in Toledo that night, but it wasn’t worth missing out on rapid testing. So at 3:30pm, we suddenly had ten hours of driving to go. We stopped in Toledo for dinner, which we ate by the waterfront. We arrived at the clinic at 4:30am, and slept in the parking lot for a few hours.",
  },
  {
    day: "day_11 - break",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/12/19",
    location: "Youngstown to Case Western Reserve University",
    miles: 69,
    captions: [],
    text:
      "We got in line at 7:30am, left around 11am, and killed time until we got our results (negative!). Highlights: fell asleep in a field outside a church near Johns Hopkins. Finally, we arrived at Ben’s apartment in Baltimore. We hung out with him for a few days, and then went to Simon’s house on August 6, thirteen days after we left Seattle! We did it!",
  },

  {
    day: "day_12",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/10/19",
    location: "Pittsburgh",
    miles: 0,
    captions: [
      "bridge",
      "city",
      "bridge",
      "bridge",
      "bridge",
      "road",
      "structures",
      "car",
      "bridge",
      "sky",
      "road",
      "sunset",
      "at orient point",
      "rocks",
      "the ferry",
    ],
    text:
      "After a week at Simon’s house, we set off on another road trip in Ran! We wanted to hit Niagara Falls, sticking to the East Coast on the way there, and visiting Pittsburgh on the way back. On August 13, we set out in the early afternoon for Orient Point, on the eastern tip of Long Island. We spent the whole day driving, getting stuck in some NYC traffic despite our efforts to avoid Manhattan. Once we were out of the city, the drive along Long Island was beautiful, especially the sunset. We stopped at Chipotle for dinner, and then at an amazing viewpoint close to the Orient Point ferry terminal that Simon remembered from his East Coast bike trek. We arrived at the terminal around 9:30pm. We parked at the edge of the lot, and then sat on the beach for a while. We slept in the car, alarms set for the 7am ferry. ",
  },
  {
    day: "day_13",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    date: "04/09/19",
    location: "Pittsburgh",
    miles: 0,
    captions: [
      "the ferry",
      "tired",
      "ferry",
      "homeless man",
      "ferry",
      "lucy cute",
      "ron in da boat",
      "new london",
      "lucy",
      "new london",
      "art",
      "new london",
      "art",
      "road",
      "boston",
      "boston",
      "bridge",
      "MIT",
      "MIT",
      "simons building",
      "MIT",
      "MIT",
      "simon in class",
      "nice",
      "pee statue",
      "building",
      "simon sanding strange",
      "boston",
      "cool bridge",
    ],
    text:
      "A chaotic and long ass day. We woke up at 6:30am, awkwardly pulling out of the parking lot and then back in while the ticketers looked on with confusion. They didn’t care though, and we got in line for the Cross Sound Ferry. We drove Ran on (no thanks to the guy who was directing traffic and made us bump Ran’s mirror) then headed up to the passenger cabin. We sat for a while, eating Chipotle leftovers and cranberry juice for breakfast. We then went out to the deck, taking pictures of the shoreline as we approached New London, CT, a perfect little port town. The captain told us to return to our vehicles, and we took some pictures of Ran on the way down (he looked so cute riding on the ferry <3). After we drove off, we went to the train station to brush our teeth, and then we walked around New London for a bit. It seemed like every other wall and intersection was decorated with a mural. Back in Ran, we navigated toward Providence, RI. We didn’t stop, just took some pictures as we drove by. Then, we drove to Boston, where our first stop was MIT. We explored the campus a bit, and I had the incredible fortune of finding a free tampon in the bathroom. Then we drove to Harvard Square, where we stopped in a CVS for our daily Gatorade. I had no idea that MIT and Harvard were right next door, so that was a cool discovery. We saw a really messed up car window (see picture), and then we were on our way to Portland, ME, where we planned to stop for lunch. Ran had other plans, though, and the battery light came on right outside Portland. A Google search couldn’t tell us what was wrong, but we did find out that most auto parts stores will do a free check of the battery-alternator system. After striking out at one store that was too busy, we ended up at an AutoZone, where they told us that the alternator was done, and we had a few hours of driving left before we fried the battery. Staying the night in Portland, then. Luckily, the guy at AutoZone recommended us to a great mechanic who ordered a new alternator right away and said he would install it early the next morning. We had a lot of trouble finding a place to stay, and when we finally did, we had to provide our recent COVID test results, which had conveniently not been uploaded online. It took us about 40 minutes to get it sorted out, all while a Karen breezed through by way of humiliating the guy at the counter. Oh well. Finally in our room, we remembered that we were starving, and rushed to a nearby Five Guys. Agreed it was probably the best meal we’d ever had. We watched Eternal Sunshine of the Spotless Mind, which was a great movie, and then had a great sleep. So, our unexpected night in Portland, ME actually turned out pretty great.",
  },
  {
    day: "day_14",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "waiting for alternator",
      "beach",
      "simon lol",
      "beach",
      "road",
      "vermont",
      "road",
      "montpelier",
      "montpelier",
      "cow",
      "art",
      "burlington",
      "architecture",
      "lucy",
      "walking with ice cream",
      "night",
      "night",
    ],
    date: "04/08/19",
    location: " Ohiopyle to Pittsburgh",
    miles: 75,
    money: 50,
    text:
      "We woke up at 9am the next morning for Ran’s 9:30 appointment. We longboarded to Dunkin’ and had really good croissant sandwiches and donuts. By the time we were finished eating, Ray (the mechanic) called and said he was done. He charged us almost nothing for labor and chose an alternator with a lifetime warranty. If you’re ever in Maine, definitely go to BroadRay Battery in Portland. We walked along the beach near Southern Maine Community College, and then we navigated to Montpelier, VT. We stopped at a diner in Littleton, NH for lunch, and then at a grocery store in Montpelier for snacks. Our next stop was Burlington, VT, but I (Lucy) messed up the navigation and we lost like an hour (oops). We showed up in Burlington around 8pm, grabbed Ben and Jerry’s (when in Vermont) and walked down to the harbor. Both Montepelier and Burlington were really pretty towns, and we had a lot of fun exploring. Leaving Burlington was unnecessarily stressful. First, when we got back to Ran, we found that the headlights were still on… luckily, he started right up. Then, the oil light came on just as we were leaving town… the oil was actually full when we pulled over and checked, but we bought some extra anyways and then headed out. On our way to Niagara Falls, we just drove until we couldn’t anymore, sleeping at a rest stop about two hours away from Niagara Falls.",
  },
  {
    day: "day_15",
    col: [[], [], []],
    popUrl: [],
    ogUrl: [],
    captions: [
      "falls",
      "water",
      "simon",
      "water",
      "water",
      "lots of water",
      "water",
      "us",
      "lookout",
      "water",
      "water",
      "more water",
      "simon",
      "lucy",
      "water",
      "water",
      "water",
      "bridge",
      "pittsburgh",
    ],
    date: "04/08/19",
    location: " Ohiopyle to Pittsburgh",
    miles: 75,
    money: 50,
    text:
      "We woke up around 9am, grabbed McDonald’s for breakfast, and then drove to Niagara Falls. It was beautiful! The lines for the attractions were way too long, but we had fun just walking around and seeing both of the falls. We saw a sign that said the daytime flow of just the American Falls is 75,000 gal/sec! After spending a couple of hours at the falls, we grabbed donuts from Tim Hortons and drove to Pittsburgh. Our first stop was Mac Miller’s Blue Slide Park, and then we grabbed some dinner from Panera. Pittsburgh is a really fun city to drive through, with all the bridges and cool views of the water. We had a really nice drive back to Frederick, taking back roads and randomly stopping at Green Ridge State Forest, which was fun but creepy in the dark. We finally made it back to Simon’s house around midnight. We did it!",
  },
];

export default days;
